version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: finguard-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: finguard_auth

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql-data: