spring.application.name=auth-service
server.port=8081
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/finguard_auth}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
jwt.secret=${JWT_SECRET:FinGuardEnterpriseSecretKeyForDevelopment123456}
spring.data.redis.host=redis
spring.data.redis.port=6379
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG
resilience4j.circuitbreaker.instances.transactionService.sliding-window-size=10
resilience4j.circuitbreaker.instances.transactionService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.transactionService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.transactionService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.transactionService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.transactionService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.loanService.sliding-window-size=10
resilience4j.circuitbreaker.instances.loanService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.loanService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.loanService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.loanService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.loanService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.retry.instances.transactionService.max-attempts=3
resilience4j.retry.instances.transactionService.wait-duration=1s
resilience4j.retry.instances.loanService.max-attempts=3
resilience4j.retry.instances.loanService.wait-duration=1s
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
info.app.name=FinGuard Auth Service
info.app.version=1.0.0
info.app.description=Enterprise Banking Microservices Application