apiVersion: v1
kind: Secret
metadata:
  name: finguard-secret
  namespace: finguard

type: Opaque

data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
  JWT_SECRET: RmluR3VhcmRFbnRlcnByaXNlU2VjcmV0S2V5Rm9yRGV2ZWxvcG1lbnQxMjM0NTY=
  MAIL_USERNAME: dmthZGFtOTkyMUBnbWFpbC5jb20=
  MAIL_PASSWORD: dXhxaHR2ZWlzdW1lZmN0Yw==