spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

info.app.name=FinGuard Eureka Server
info.app.version=1.0.0
info.app.description=Enterprise Banking Microservices Application
management.info.env.enabled=true